### ISSUE TITLE
Photography assets are in git when the granted license does not allow it

### ISSUE THREAD

**Issue by davidjrichardson** [UWCS/warwickspeedrun#15]
The photos from WASD 2020, currently used on the website, were provided to WASD under the premise that they'd be left out of Git. Unfortunately this was missed when the site got re-built from the [previous system](https://github.com/davidjrichardson/warwickspeedrun).

You need to remove them from Git + any history that includes them. Simple as that.

**Comment by Levelent** [comment]
Was fixed a couple months ago, seems like no-one closed it - apologies!
